const { pool } = require('../Connexion/Db')
const express = require('express')
const path = require('path')
const multer = require('multer')
const app = express()
const uploadDirectory = path.join(_dirname, 'uploads')